#[package]
# name = "redo"
# version = "0.1.0"
# edition = "2021"
#
# [dependencies]
# crossterm = "0.28.1"

[workspace]
members=["redo", "tui", "dummy"]
default-members=["tui"]
resolver="2"
[workspace.dependencies]
redo={path="redo"}
